apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-webapp
  template:
    metadata:
      labels:
        app: flask-webapp
    spec:
      containers:
      - name: flask-webapp
        image: gpohren/flask-webapp:dev
---
apiVersion: v1
kind: Service
metadata:
  name: flask-webapp-svc
spec:
  type: LoadBalancer
  selector:
    app: flask-webapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080
